apiVersion: operator.example.com/v1alpha1
kind: MyNginxOperator
metadata:
  labels:
    app.kubernetes.io/name: nginxoperator
    app.kubernetes.io/managed-by: kustomize
  name: mynginxoperator-sample
spec:
  # TODO(user): Add fields here
